%% Run AFNI's surface cluster correction
% https://afni.nimh.nih.gov/pub/dist/doc/program_help/slow_surf_clustsim.py.html
% message board post with some info: https://afni.nimh.nih.gov/afni/community/board/read.php?1,159863,159889#msg-159889
purge
clust_dir = '/Volumes/NBL_Projects/NSF_SNP/Processed_Data/GroupLevel_Surface_Results/ClustSim_Surface';
cd(clust_dir);
hemi = {'lh','rh'};
iters = 10000;
str = '10k';
for ii = 1:numel(hemi)
    % Run the setup script
    unix(['slow_surf_clustsim.py -save_script surf.' hemi{ii} '.' str '.clustsim'...
            ' -on_surface yes'...
            ' -uvar blur 6.0'...
            ' -uvar niter ' num2str(iters)...
            ' -uvar spec_file SUMA/std.141.' hemi{ii} '.spec'...
            ' -uvar surf_vol SUMA/SNP110_SurfVol.nii'...
            ' -uvar surf_mask '
            ' -uvar pthr_list 0.01 0.005 0.001 0.0005 0.0001'...
            ' -uvar results_dir ' clust_dir '/' hemi{ii} '.' str...
            ' -verb 1']);
    % Actually run processing script
    unix(['tcsh -xef surf.' hemi{ii} '.' str '.clustsim']);
end
