%% Make circular ROIs at calculated FS region centers for verification

out_dir = '/Volumes/NBL_Projects/Price_NFA/Analyses_for_Paper/FreeSurfer_ROIs';
cd(out_dir);

mesh = '60';%'141';

% LH
T = readtable(['FS_ROI_centers_lh_' mesh '.txt']);
writematrix(T.Var4,['FS_lh_center_nodes_' mesh '.txt']);
writematrix(ones(height(T),1),'FS_lh_center_node_tmpval.txt');
% RH
T = readtable(['FS_ROI_centers_rh_' mesh '.txt']);
writematrix(T.Var4,['FS_rh_center_nodes_' mesh '.txt']);
writematrix(ones(height(T),1),'FS_rh_center_node_tmpval.txt');


hemi = 'lh';
out = 'FS_lh_centers';
MNI_dir = '/Users/benconrad/.afni/data/suma_MNI152_2009';
sid = 'MNI152_2009';
spec = ['std.' mesh '.' sid '_' hemi '.spec']; % Surface spec file
surf = ['std.' mesh '.' hemi '.inflated.gii']; % Surface to "grow" ROIs on
d = '5';
cd(MNI_dir);
unix(['ROIgrow -overwrite'...
    ' -insphere ' d...
    ' -spec ' spec ...
    ' -surf ' surf ...
    ' -roi_nodes ' out_dir '/FS_lh_center_nodes_' mesh '.txt'...
    ' -roi_labels ' out_dir '/FS_lh_center_node_tmpval.txt'...
    ' -prefix ' out_dir '/' out '.inflated.' mesh '.' d 'mm_diam']);


hemi = 'rh';
out = 'FS_rh_centers';
spec = ['std.' mesh '.' sid '_' hemi '.spec']; % Surface spec file
surf = ['std.' mesh '.' hemi '.inflated.gii']; % Surface to "grow" ROIs on
unix(['ROIgrow -overwrite'...
    ' -insphere ' d...
    ' -spec ' spec ...
    ' -surf ' surf ...
    ' -roi_nodes ' out_dir '/FS_rh_center_nodes_' mesh '.txt'...
    ' -roi_labels ' out_dir '/FS_rh_center_node_tmpval.txt'...
    ' -prefix ' out_dir '/' out '.inflated.' mesh '.' d 'mm_diam']);


%% Convert to NIML
cd(out_dir);
unix(['ConvertDset -pad_to_node ld141 -o_niml '...
     ' -node_index_1D FS_lh_centers.inflated.' mesh '.' d 'mm_diam.1.1D[0]'...
     ' -input FS_lh_centers.inflated.' mesh '.' d 'mm_diam.1.1D[1]'...
     ' -prefix FS_lh_centers.inflated.' mesh '.' d 'mm_diam']);
 
unix(['ConvertDset -pad_to_node ld141 -o_niml '...
     ' -node_index_1D FS_rh_centers.inflated.' mesh '.' d 'mm_diam.1.1D[0]'...
     ' -input FS_rh_centers.inflated.' mesh '.' d 'mm_diam.1.1D[1]'...
     ' -prefix FS_rh_centers.inflated.' mesh '.' d 'mm_diam']);