%% Use ROIgrow command to create circular ROIs on the cortical surfaces from FreeSurfer
% Center on standard surface (std.141 density) nodes based on Pollack &
% Price 2019, NeuroImage
purge

DpDa = '/Volumes/NBL_Projects/Price_NFA/Software+Code/matfiles/anatomical_rois/std.141.PP19_Dp-Da_lh_node170106';
LpLa = '/Volumes/NBL_Projects/Price_NFA/Software+Code/matfiles/anatomical_rois/std.141.PP19_Lp-La_lh_node171619';
DpDa_R = '/Volumes/NBL_Projects/Price_NFA/Software+Code/matfiles/anatomical_rois/std.141.PP19_Dp-Da_rh_node154269';
LpLa_R = '/Volumes/NBL_Projects/Price_NFA/Software+Code/matfiles/anatomical_rois/std.141.PP19_Lp-La_rh_node30120';
diam = '14';

cd('/Volumes/NBL_Projects/Price_NFA/NFA_fMRI/ProcessedData');
sub_dirs = dir('*_proc');

% Loop through subjects
for ii = 1:numel(sub_dirs)
    % Get subject ID and go to freesurfer SUMA folder
    sid = strsplit(sub_dirs(ii).name,'_'); sid = sid{1,1};
    disp(['** Working on subject ' sid '... **']);
    cd(['/Volumes/NBL_Projects/Price_NFA/NFA_fMRI/ProcessedData/' sid '_proc/' sid '.freesurfer/SUMA']); 
    
    % Create circular ROI on the surface, around selected node in each
    % hemisphere
    spec = ['std.141.' sid '_lh.spec']; % Surface spec file
    surf = 'std.141.lh.inflated.gii'; % Surface to "grow" ROIs on
    unix(['ROIgrow -overwrite'... 
          ' -insphere ' diam...
          ' -spec ' spec...
          ' -surf ' surf...
          ' -roi_nodes ' DpDa '.txt'... 
          ' -roi_labels ' DpDa '_label.txt'...
          ' -prefix std.141.lh.PP19_Dp-Da.MNI152.votc.inflated.' diam 'mm_diam']);
    unix(['ROIgrow -overwrite'... 
          ' -insphere ' diam...
          ' -spec ' spec...
          ' -surf ' surf...
          ' -roi_nodes ' LpLa '.txt'... 
          ' -roi_labels ' LpLa '_label.txt'...
          ' -prefix std.141.lh.PP19_Lp-La.MNI152.votc.inflated.' diam 'mm_diam']);
      
    spec = ['std.141.' sid '_rh.spec']; % Surface spec file
    surf = 'std.141.rh.inflated.gii'; % Surface to "grow" ROIs on  
    unix(['ROIgrow -overwrite'... 
          ' -insphere ' diam...
          ' -spec ' spec...
          ' -surf ' surf...
          ' -roi_nodes ' DpDa_R '.txt'... 
          ' -roi_labels ' DpDa_R '_label.txt'...
          ' -prefix std.141.rh.PP19_Dp-Da.MNI152.votc.inflated.' diam 'mm_diam']);
    unix(['ROIgrow -overwrite'... 
          ' -insphere ' diam...
          ' -spec ' spec...
          ' -surf ' surf...
          ' -roi_nodes ' LpLa_R '.txt'... 
          ' -roi_labels ' LpLa_R '_label.txt'...
          ' -prefix std.141.rh.PP19_Lp-La.MNI152.votc.inflated.' diam 'mm_diam']);
end
  
